### ISSUE TITLE
myEvolv SQL Server database | Tables, Primary, and Foreign Keys: Excel Workbook / Spreadsheet

### ISSUE THREAD

**Issue by WMMHC1** [myEvolv-Development-Community/myEvolvCode#10]
#  ❓ ❓  ** Help!! ** ❓ ❓

#### Thanks! 
# 🎆

**Comment by cc-jdurbin** [comment]
The linked view definitions may be helpful:

[data schema](https://github.com/myEvolv-Development-Community/myEvolvCode/blob/main/SQL%20Views/Get%20Data%20Schema.md)

[foreign key references](https://github.com/myEvolv-Development-Community/myEvolvCode/blob/main/SQL%20Views/Get%20Foreign%20and%20Primary%20Keys.md)

Let me know if there's anything else you need. If not, feel free to close the issue.

**Comment by WMMHC1** [comment]
Awesome thank you!
