### ISSUE TITLE
Add assets/images directory to JavaScript Functions

### ISSUE THREAD

**Issue by Khoirovoskos** [myEvolv-Development-Community/myEvolvCode#46]
I think we should add an images folder to JavaScript functions. Some of the demo pages included image links, which are broken because that folder did not migrate over, and feedback from the community has suggested images would be helpful to illustrate what effects users should anticipate with the code provided.

Does anyone have objections to me adding this directory to the site?

**Comment by cc-jdurbin** [comment]
I don't have an issue with it! The SQL directory has that, so why not JavaScript as well.
