### ISSUE TITLE
Subreport Hyperlink to Editable Form questions

### ISSUE THREAD

**Issue by MichaelHoward-UCAN** [myEvolv-Development-Community/myEvolvCode#56]
In NX, I'm trying to open an editable from from a subreport hyperlink on a service form opened from the Service Entry formset member.  

I tried to implement both the JavaScript Functions/Subreport Hyperlink to Editable Form.md code as well as the SQL Views
/Hyperlink to Editable Form (View).md code.  In both cases, the form opens successfully and allows editing, but there are different issues with each when I close the form.

With the Javascript solution, when I close the form opened by the subreport, it does appropriately return me to the service form containing the subreport.  However, when I close the service form with the subreport, instead of being returned to the Service Entry formset member, I'm returned to the form opened by the subreport.  In actuality, there are about six instances of this form that apparently have been opened by the JavaScript.  Eventually, if I close all such instances of the form, I'm returned to the Service Entry formset member.

As a side note on the Javascript solution, I noticed that the referenced link to the vv_event_forms_expanded view (https://github.com/Khoirovoskos/Example-Code-Repo/blob/main/SQL%20Functions/Event%20Forms%20View.md) is broken, but in looking at the Javascript code, I could construct a virtual view that allowed the retrieval of the appropriate form code.

In the SQL View solution, with a hyperlink included as a subreport memo column, again the editable form is appropriately opened and allows the editing and saving of data.  However, when I close the form opened by the subreport link, instead of returning me to the service form containing the subreport, I'm returned immediately to the Service Entry formset member.

Any ideas or explanation would be appreciated.

**Comment by Khoirovoskos** [comment]
The expected behavior would be for the linked form to open in a new window or tab, and to return to the form containing the subreport on close. In my system, the JavaScript solution seems to do just that, but it may be a difference in versions or network speed at play.

I corrected the hyperlink in the documentation for the JavaScript solution.

As for the SQL View, I added `target="_blank"` to the hyperlink tag to prompt it to open the form in a new browser tab. Please try the updated view definition and let us know whether it works.

**Comment by MichaelHoward-UCAN** [comment]
The modification for SQL view approach did the trick for us.  It now opens in its own tab and closing that tab has no impact (adverse or otherwise) on the tab/form that opened it.

Thank you.  I'm very happy with this.  FYI, the code solution, which for me seemingly opens several instances of the desired form, does so as child(?) windows of the existing tab, not as new tabs.  Aside from the Evolv version/release (or my errors in implementation), I wonder if there could be browser or browser settings that could explain the variance.  We're on 11.0.0050.03.
